vim.keymap.set("n", "<down>", "<Plug>CoqNext")
vim.keymap.set("n", "<up>",   "<Plug>CoqUndo")
vim.keymap.set("n", "s", "<Plug>CoqNext")
vim.keymap.set("n", "S", "<Plug>CoqUndo")
vim.keymap.set("n", "L", "<Plug>CoqToLine")
