vim.keymap.set("v", "<C-b>", "<Plug>(sandwich-add)ctextbf<cr>")
vim.keymap.set("v", "<C-i>", "<Plug>(sandwich-add)ctextit<cr>")
vim.keymap.set("v", "<C-t>", "<Plug>(sandwich-add)ctexttt<cr>")
vim.keymap.set("n", "<leader>i", "i~$$<esc>i")
vim.keymap.set("n", "<leader>vc", vim.cmd("VimtexCompile"))
