vim.keymap.set("v", "<localleader>b", "<Plug>(sandwich-add)ctextbf<cr>")
vim.keymap.set("v", "<localleader>i", "<Plug>(sandwich-add)ctextit<cr>")
vim.keymap.set("v", "<localleader>t", "<Plug>(sandwich-add)ctexttt<cr>")
vim.keymap.set("n", "<leader>i", "i~$$<esc>i")
vim.keymap.set("n", "<localleader>tc", vim.cmd("VimtexCompile"))
