SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_ORDER=(
    dir
    git
    sudo
    exec_time
    char
)

SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL_SUCCESS="➜"
SPACESHIP_CHAR_SYMBOL_FAILURE="✗"

SPACESHIP_DIR_TRUNC=5
SPACESHIP_DIR_TRUNC_PREFIX="…/"
# SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_LOCK_SYMBOL=" "

SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_ASYNC=false
# SPACESHIP_GIT_PREFIX="git:("
# SPACESHIP_GIT_SUFFIX=")"
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SUFFIX=" "
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_ASYNC=false
SPACESHIP_GIT_BRANCH_SUFFIX=""
