#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

sudo yabai --load-sa

yabai -m config                                    \
         mouse_follows_focus          off          \
         focus_follows_mouse          autofocus    \
         window_placement             second_child \
         window_topmost               off          \
         window_shadow                on           \
         window_opacity               off          \
         active_window_opacity        1.0          \
         normal_window_opacity        0.90         \
         window_border                off          \
         window_border_width          6            \
         active_window_border_color   0xff775759   \
         normal_window_border_color   0xff555555   \
         insert_feedback_color        0xffd75f5f   \
         split_ratio                  0.50         \
         auto_balance                 off          \
         mouse_modifier               fn           \
         mouse_action1                move         \
         mouse_action2                resize       \
         mouse_drop_action            swap         \
         external_bar                 all:0:0      \
         layout                       bsp          \
         top_padding                  3            \
         bottom_padding               3            \
         left_padding                 3            \
         right_padding                3            \
         window_gap                   3

yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Réglages Système$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title="Preferences$" manage=off



# yabai -m config window_opacity_duration      0.0

echo "yabai configuration loaded.."
