# ~/.config/himalaya/config.toml

name = "Paul Patault"
downloads-dir = "~/Downloads"
signature = """
Bien cordialement,

Paul Patault
"""

# [gmail]
# default = true
# email = "p.patault@gmail.com"

# imap-host = "imap.gmail.com"
# imap-port = 993
# imap-login = "p.patault@gmail.com"
# imap-passwd-cmd = "security find-generic-password -a p.patault -s gmail -w"

# smtp-host = "smtp.gmail.com"
# smtp-port = 465
# smtp-login = "p.patault@gmail.com"
# smtp-passwd-cmd = "security find-generic-password -a p.patault -s gmail -w"

[zimbra]
default = true
email = "paul.patault@universite-paris-saclay.fr"

imap-host = "hermes.universite-paris-saclay.fr"
imap-port = 993
imap-login = "paul.patault"
imap-passwd-cmd = "security find-generic-password -a p.patault -s zimbra -w"

smtp-host = "smtps.universite-paris-saclay.fr"
smtp-port = 465
smtp-login = "paul.patault"
smtp-passwd-cmd = "security find-generic-password -a p.patault -s zimbra -w"
