lastupdatecheck: 0
recentrepos:
- /Users/paulpatault/MPRI
- /Users/paulpatault/Dev/Ocaml/Bazaar
- /Users/paulpatault/dotfiles
- /Users/paulpatault/stage-gospel/gospel
- /Users/paulpatault/stage-gospel
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
