lastupdatecheck: 0
recentrepos:
- /Users/paulpatault/dotfiles
- /Users/paulpatault/d/w/theatredulabyrinthe
- /Users/paulpatault/d/tex/CV
- /Users/paulpatault/d/web/theatredulabyrinthe
- /Users/paulpatault/stage
- /Users/paulpatault/mpri
- /Users/paulpatault/stage/gospel
- /Users/paulpatault/MPRI
- /Users/paulpatault/stage-gospel/gospel
- /Users/paulpatault/d/ocaml/why3
- /Users/paulpatault/stage-gospel
- /Users/paulpatault/d/ocaml/vim-ocaml
- /Users/paulpatault/Dev/Ocaml/Bazaar
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
