lastupdatecheck: 1653687934
recentrepos:
- /Users/paulpatault/dotfiles
- /Users/paulpatault/stage
- /Users/paulpatault/stage/gospel
- /Users/paulpatault/d/ocaml/texplate
- /Users/paulpatault/m2
- /Users/paulpatault/d/tex/CV
- /Users/paulpatault/d/w/theatredulabyrinthe
- /Users/paulpatault/Desktop/Candidatures 2022
- /Users/paulpatault/d/ocaml/bazaar
- /Users/paulpatault/mpri
- /Users/paulpatault/d/web/theatredulabyrinthe
- /Users/paulpatault/MPRI
- /Users/paulpatault/stage-gospel/gospel
- /Users/paulpatault/d/ocaml/why3
- /Users/paulpatault/stage-gospel
- /Users/paulpatault/d/ocaml/vim-ocaml
- /Users/paulpatault/Dev/Ocaml/Bazaar
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
