lastupdatecheck: 0
recentrepos:
- /Users/paulpatault/dotfiles
- /Users/paulpatault/stage-gospel/gospel
- /Users/paulpatault/d/ocaml/why3
- /Users/paulpatault/stage-gospel
- /Users/paulpatault/d/ocaml/vim-ocaml
- /Users/paulpatault/MPRI
- /Users/paulpatault/Dev/Ocaml/Bazaar
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
